# Pandas 
```
pip install pandas 
pip install --upgrade pandas
```
- Pandas Series
- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- Add a column: using name and list
- shape
- head
- tail
- convert to numpy array --> values
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  columns.get_loc
-  Fancy indexing
-  Filtering
-  unique
-  sort_values(by,ascending)
-  getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib
- 

In [1]:
import pandas as pd
import numpy as np

In [37]:
print(pd.__version__)
pd.DF = pd.DataFrame

2.2.3


In [3]:
l1 = np.array([10,20,30,40,50])
d1 = {'A':20,'B':100,'C':10}

In [18]:
# pds = pd.Series(l1,index=['A','B','C','D','E'],dtype='f8')
pds = pd.Series(d1)

In [19]:
pds

A     20
B    100
C     10
dtype: int64

In [20]:
type(pds)

pandas.core.series.Series

In [21]:
pds['A']

20

In [22]:
marks = {
    'Phy':[80,98,84,75,92],
    'Chem':[92,96,95,80,72],
    'Maths':[100,88,91,95,82]
}

In [23]:
marks

{'Phy': [80, 98, 84, 75, 92],
 'Chem': [92, 96, 95, 80, 72],
 'Maths': [100, 88, 91, 95, 82]}

In [33]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'],columns=['Maths','Phy','Chem'])

In [34]:
df

Maths  Phy  Chem
A    100   80    92
B     88   98    96
C     91   84    95
D     95   75    80
E     82   92    72

In [26]:
df['Phy']

0    80
1    98
2    84
3    75
4    92
Name: Phy, dtype: int64

In [36]:
na = np.random.randint(50,101,size = (10,3))
na

array([[82, 89, 51],
       [70, 92, 92],
       [98, 50, 69],
       [59, 65, 85],
       [52, 86, 58],
       [68, 86, 74],
       [68, 99, 58],
       [94, 75, 78],
       [65, 63, 99],
       [50, 96, 94]])

In [42]:
df2 = pd.DF(na,columns=['OS','DBMS','CN'],dtype='f8')

In [43]:
df2

OS  DBMS    CN
0  82.0  89.0  51.0
1  70.0  92.0  92.0
2  98.0  50.0  69.0
3  59.0  65.0  85.0
4  52.0  86.0  58.0
5  68.0  86.0  74.0
6  68.0  99.0  58.0
7  94.0  75.0  78.0
8  65.0  63.0  99.0
9  50.0  96.0  94.0

In [44]:
df2['CA'] = np.random.randint(51,101,size=(10,))

In [45]:
df2

OS  DBMS    CN  CA
0  82.0  89.0  51.0  56
1  70.0  92.0  92.0  78
2  98.0  50.0  69.0  70
3  59.0  65.0  85.0  76
4  52.0  86.0  58.0  85
5  68.0  86.0  74.0  54
6  68.0  99.0  58.0  84
7  94.0  75.0  78.0  69
8  65.0  63.0  99.0  85
9  50.0  96.0  94.0  85

In [46]:
df2.shape

(10, 4)

In [47]:
df2['CA']

0    56
1    78
2    70
3    76
4    85
5    54
6    84
7    69
8    85
9    85
Name: CA, dtype: int32

In [48]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   OS      10 non-null     float64
 1   DBMS    10 non-null     float64
 2   CN      10 non-null     float64
 3   CA      10 non-null     int32  
dtypes: float64(3), int32(1)
memory usage: 412.0 bytes


In [50]:
df2.head(3)

OS  DBMS    CN  CA
0  82.0  89.0  51.0  56
1  70.0  92.0  92.0  78
2  98.0  50.0  69.0  70

In [51]:
df2.tail(3)

OS  DBMS    CN  CA
7  94.0  75.0  78.0  69
8  65.0  63.0  99.0  85
9  50.0  96.0  94.0  85

In [52]:
df.values

array([[100,  80,  92],
       [ 88,  98,  96],
       [ 91,  84,  95],
       [ 95,  75,  80],
       [ 82,  92,  72]], dtype=int64)

In [54]:
df2.columns

Index(['OS', 'DBMS', 'CN', 'CA'], dtype='object')

In [56]:
df.columns

Index(['Maths', 'Phy', 'Chem'], dtype='object')

In [57]:
df

Maths  Phy  Chem
A    100   80    92
B     88   98    96
C     91   84    95
D     95   75    80
E     82   92    72

In [58]:
df.to_csv("Marks.csv")

In [65]:
ndf = pd.read_csv('Marks.csv',index_col='Unnamed: 0')

In [66]:
ndf

Maths  Phy  Chem
A    100   80    92
B     88   98    96
C     91   84    95
D     95   75    80
E     82   92    72

In [88]:
df.to_csv("Marks.csv",sep='|',index = False)

In [89]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

Maths  Phy  Chem
0    100   80    92
1     88   98    96
2     91   84    95
3     95   75    80
4     82   92    72

In [93]:
ndf.index = ['A','B','C','D','E']

In [94]:
ndf

Maths  Phy  Chem
A    100   80    92
B     88   98    96
C     91   84    95
D     95   75    80
E     82   92    72

In [95]:
df

Maths  Phy  Chem
A    100   80    92
B     88   98    96
C     91   84    95
D     95   75    80
E     82   92    72

In [98]:
df2

OS  DBMS    CN  CA
0  82.0  89.0  51.0  56
1  70.0  92.0  92.0  78
2  98.0  50.0  69.0  70
3  59.0  65.0  85.0  76
4  52.0  86.0  58.0  85
5  68.0  86.0  74.0  54
6  68.0  99.0  58.0  84
7  94.0  75.0  78.0  69
8  65.0  63.0  99.0  85
9  50.0  96.0  94.0  85

In [99]:
df2.astype('i8')

OS  DBMS  CN  CA
0  82    89  51  56
1  70    92  92  78
2  98    50  69  70
3  59    65  85  76
4  52    86  58  85
5  68    86  74  54
6  68    99  58  84
7  94    75  78  69
8  65    63  99  85
9  50    96  94  85

In [110]:
df

Maths  Phy  Chem
A    100   80    92
B     88   98    96
D     95   75    80
E     82   92    72

In [109]:
# df.drop(columns=['Chem'])
df.drop(index=['C'],inplace=True)

Maths  Phy  Chem
B     88   98    96
D     95   75    80
E     82   92    72

In [111]:
df2

OS  DBMS    CN  CA
0  82.0  89.0  51.0  56
1  70.0  92.0  92.0  78
2  98.0  50.0  69.0  70
3  59.0  65.0  85.0  76
4  52.0  86.0  58.0  85
5  68.0  86.0  74.0  54
6  68.0  99.0  58.0  84
7  94.0  75.0  78.0  69
8  65.0  63.0  99.0  85
9  50.0  96.0  94.0  85

In [112]:
df2.describe()

OS     DBMS         CN         CA
count  10.000000  10.0000  10.000000  10.000000
mean   70.600000  80.1000  75.800000  74.200000
std    16.256281  16.1689  16.731872  11.773794
min    50.000000  50.0000  51.000000  54.000000
25%    60.500000  67.5000  60.750000  69.250000
50%    68.000000  86.0000  76.000000  77.000000
75%    79.000000  91.2500  90.250000  84.750000
max    98.000000  99.0000  99.000000  85.000000

In [113]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   OS      10 non-null     float64
 1   DBMS    10 non-null     float64
 2   CN      10 non-null     float64
 3   CA      10 non-null     int32  
dtypes: float64(3), int32(1)
memory usage: 412.0 bytes


In [117]:
df2[['CA','OS']]

CA    OS
0  56  82.0
1  78  70.0
2  70  98.0
3  76  59.0
4  85  52.0
5  54  68.0
6  84  68.0
7  69  94.0
8  85  65.0
9  85  50.0

In [122]:
df2.iloc[2:7,[0,2]]

OS    CN
2  98.0  69.0
3  59.0  85.0
4  52.0  58.0
5  68.0  74.0
6  68.0  58.0

In [123]:
df

Maths  Phy  Chem
A    100   80    92
B     88   98    96
D     95   75    80
E     82   92    72

In [124]:
df.iloc[0:2]

Maths  Phy  Chem
A    100   80    92
B     88   98    96

In [126]:
df.loc[['A','E'],['Phy','Chem']]

Phy  Chem
A   80    92
E   92    72

In [127]:
df.loc['A':'D']

Maths  Phy  Chem
A    100   80    92
B     88   98    96
D     95   75    80

In [129]:
df2.loc[0:4]

OS  DBMS    CN  CA
0  82.0  89.0  51.0  56
1  70.0  92.0  92.0  78
2  98.0  50.0  69.0  70
3  59.0  65.0  85.0  76
4  52.0  86.0  58.0  85

In [131]:
df[[True,True,False,True]]

Maths  Phy  Chem
A    100   80    92
B     88   98    96
E     82   92    72

In [136]:
df['Phy']-10

A    70
B    88
D    65
E    82
Name: Phy, dtype: int64

In [135]:
wdf = pd.read_csv('weather_data_cities.csv')

In [144]:
mumbaidf = wdf[wdf['city'] == 'mumbai']

In [146]:
mumbaidf[mumbaidf['temperature'] >= 90]['day']

4    1/1/2017
7    1/4/2017
Name: day, dtype: object

In [166]:
wdf[(wdf['city'] == 'mumbai') & (wdf['temperature'] >= 90)]

day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
7  1/4/2017  mumbai           92          5   Rain

In [168]:
wdf.columns.get_loc('city')

1

In [109]:
df[df['Phy'] >= 73]

Phy  Chem  Maths
A   74    41     65
D   98    56     56

In [119]:
df.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [112]:
df.columns.get_loc('Maths')

2

In [169]:
df

Phy  Maths
A   85    100
B   95     79
C   90     94
D   65     83
E   78     80

In [170]:
df['Phy'].unique()

array([85, 95, 90, 65, 78], dtype=int64)

In [175]:
pd.unique(df['Phy'])

array([85, 95, 90, 65, 78], dtype=int64)

In [171]:
a = np.array([1,3,1,2,4,1,3,2,4,1,2,3,1,4])

In [173]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4]), array([5, 3, 3, 3], dtype=int64))

In [179]:
df2['Chemistry'].apply(lambda x: x**2)

0      81
1    1156
2    3364
3    7056
4     400
5    2704
6    7056
7    2500
8     225
9    1764
Name: Chemistry, dtype: int64

In [181]:
df.sort_values(by = 'Phy',axis = 0,ascending=False)

Phy  Maths
B   95     79
C   90     94
A   85    100
E   78     80
D   65     83

In [182]:
df.sort_values(by = 'A',axis = 1,ascending=False)

Maths  Phy
A    100   85
B     79   95
C     94   90
D     83   65
E     80   78

In [183]:
pds = pd.Series(['A','B','C','B','A','B'])

In [189]:
pds

0    A
1    B
2    C
3    B
4    A
5    B
dtype: object

In [191]:
pdd = pd.get_dummies(pds,dtype='i1',prefix='y')

In [192]:
pdd

y_A  y_B  y_C
0    1    0    0
1    0    1    0
2    0    0    1
3    0    1    0
4    1    0    0
5    0    1    0

In [193]:
data = pd.read_csv("weather_data_cities.csv")

In [194]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [195]:
data.iloc[data['temperature'].argmax()]

day            1/4/2017
city             mumbai
temperature          92
windspeed             5
event              Rain
Name: 7, dtype: object

In [152]:
data[data['temperature'] == data['temperature'].max()]

day    city  temperature  windspeed event
7  1/4/2017  mumbai           92          5  Rain

In [199]:
gdf = data.groupby(by = 'city')

In [200]:
for city,group in gdf:
    print(city)
    print(group)
    print()

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy



In [201]:
gdf['temperature'].max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

In [202]:
gdf = data.groupby(by = 'event')
gdf['windspeed'].mean()

event
Cloudy    10.333333
Fog       13.500000
Rain       5.500000
Snow      12.000000
Sunny      9.750000
Name: windspeed, dtype: float64

In [165]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [206]:
data.pivot(columns='city',index='day')

temperature                windspeed                 event           \
city          mumbai new york paris    mumbai new york paris mumbai new york   
day                                                                            
1/1/2017          90       32    45         5        6    20  Sunny     Rain   
1/2/2017          85       36    50        12        7    13    Fog    Sunny   
1/3/2017          87       28    54        15       12     8    Fog     Snow   
1/4/2017          92       33    42         5        7    10   Rain    Sunny   

                  
city       paris  
day               
1/1/2017   Sunny  
1/2/2017  Cloudy  
1/3/2017  Cloudy  
1/4/2017  Cloudy

In [207]:
d1 = {
    'A' : [10,20,30,40],
    'B' : [3,4,5,6]
}
d2 = {
    'A' : [30,40,50,60],
    'C' : [3,4,5,6]
}

In [208]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [209]:
df1

A  B
0  10  3
1  20  4
2  30  5
3  40  6

In [210]:
df2

A  C
0  30  3
1  40  4
2  50  5
3  60  6

In [214]:
df3 = pd.concat([df1,df2],axis=1)
df3

A  B   A  C
0  10  3  30  3
1  20  4  40  4
2  30  5  50  5
3  40  6  60  6

In [219]:
mdf3 = pd.merge(df1,df2,how='right')
mdf3

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  NaN  5
3  60  NaN  6

In [220]:
mdf3.dropna()

A    B  C
0  30  5.0  3
1  40  6.0  4

In [221]:
mdf3.fillna(mdf3.mean())

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  5.5  5
3  60  5.5  6

In [222]:
mdf3.mean()

A    45.0
B     5.5
C     4.5
dtype: float64

In [223]:
mdf3.interpolate('linear',limit_direction='both')

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  6.0  5
3  60  6.0  6

In [196]:
arr = np.array([1,2,3,2,3])
arr.argmax()

2